feat(enhanced websocket)
helius-labs/helius-rust-sdk pull request #19
Opened 2024-05-15 19:13 UTC by 0xBreath

Added support for [geyser enhanced websockets](https://docs.helius.dev/webhooks-and-websockets/websockets#helius-geyser-enhanced-websockets-beta).

There are two methods each with an example:
- [Transaction subscription](https://github.com/0xBreath/helius-rust-sdk/blob/enhanced-ws/examples/enhanced_websocket_accounts.rs)
- [Account subscription](https://github.com/0xBreath/helius-rust-sdk/blob/enhanced-ws/examples/enhanced_websocket_transactions.rs)

Tests pass, cargo fmt has been run, and all warnings have been cleaned.

2024-05-16 20:10 UTC, 0xIchigo requested changes
Very based! The code is solid overall, I just have a few nitpicks here and there that could improve its overall quality. Also, I've tested the examples with a few real-world calls and can ensure that it works as intended. If possible, it would be nice if you could write up some test cases for `transactionSubscribe` and `accountSubscribe` in a `test/test_websocket.rs` file

2024-05-16 20:10 UTC, 0xIchigo commented on .gitignore
Can you remove this from the `.gitignore`, please, and just refrain from committing any code you have in your `idea` directory? Not sure if it makes sense for this to be put into prod

2024-05-16 20:10 UTC, 0xIchigo commented on examples/enhanced_websocket_accounts.rs
> +async fn main() -> Result<(), HeliusError> {
We have a handy [`Result` type alias](https://github.com/helius-labs/helius-rust-sdk/blob/7b24e7af014e79ee5ed1e07a20092c0549d58564/src/error.rs#L101-L102) that could be used here, so it gets shortened to `Result<()>`

2024-05-16 20:10 UTC, 0xIchigo commented on examples/enhanced_websocket_transactions.rs
> +async fn main() -> Result<(), HeliusError> {
The `Result` type alias can also be used here

2024-05-16 20:10 UTC, 0xIchigo commented on src/client.rs
> +    pub async fn new_with_ws(api_key: &str, cluster: Cluster) -> Result<Self> {
Can you add some documentation here for the new method, please?

2024-05-16 20:10 UTC, 0xIchigo commented on src/error.rs
> +    #[error("unable to connect to server: {0}")]
Can you ensure the error messages are properly capitalized please? That way, this one would read `"Unable to connect to server: {0}"`

2024-05-16 20:10 UTC, 0xIchigo commented on src/websocket.rs
> +            let node_version = self.get_version().await?;
This could be handled more gracefully by returning a specific error if it fails to get the node version

2024-05-16 20:10 UTC, 0xIchigo commented on src/websocket.rs
> +              // Send `Message::Ping` each 10s if no any other communication
The ping duration could be extracted and declared as a constant for better readability and easier configuration, if we want to change it in the future

2024-05-16 20:10 UTC, 0xIchigo commented on src/websocket.rs
> +#![allow(dead_code)]
Can you remove this and clean up the relevant dead code, please?

2024-05-16 20:10 UTC, 0xIchigo commented on src/websocket.rs
> +pub type EnhancedWebsocketResult<T = ()> = Result<T, HeliusError>;
This could be cleaned up using the `Result` type alias mentioned earlier

2024-05-16 20:10 UTC, 0xIchigo commented on src/websocket.rs
> +impl EnhancedWebsocket {
More fleshed-out documentation for these new methods would be greatly appreciated

2024-05-16 20:10 UTC, 0xIchigo commented on src/websocket.rs
> +                reason: format!("failed to parse cluster version: {e}"),
Can you capitalize this please so it reads `"Failed to parse cluster..."`

2024-05-27 15:16 UTC, 0xIchigo commented on .gitignore
On second thought, disregard this comment lol all good!

2024-05-27 17:28 UTC, 0xBreath commented on examples/enhanced_websocket_accounts.rs
> +async fn main() -> Result<(), HeliusError> {
I copied and pasted from your other tests. Ctrl+F for `Result<(), HeliusError`.
I'll use your result, but also modify your existing tests for consistency.

2024-06-04 18:04 UTC, merged