Webhook test
helius-labs/helius-rust-sdk pull request #24
Opened 2024-05-20 20:03 UTC by davidkathoh

Added EnhanceTransaction and Webhook test #15

2024-05-23 21:33 UTC, 0xIchigo requested changes
Based PR. I've requested a few small changes, but very nice overall! 🔥

2024-05-23 21:33 UTC, 0xIchigo commented on .idea/.gitignore
Can you please remove this file from the PR? It might be prudent to add the `.idea` directory to the `.gitignore` file so this doesn't happen in the future

2024-05-23 21:33 UTC, 0xIchigo commented on .idea/helius-rust-sdk.iml
Can you please remove this file from the PR?

2024-05-23 21:33 UTC, 0xIchigo commented on .idea/modules.xml
Can you please remove this file from the PR?

2024-05-23 21:33 UTC, 0xIchigo commented on .idea/vcs.xml
Can you please remove this file from the PR?

2024-05-23 21:33 UTC, 0xIchigo commented on tests/test_enhanced_transactions.rs
> +    let mock = server
This is an unused variable. I think you might have meant to do `server.mock()` instead of declaring it as `mock`

2024-05-23 21:33 UTC, 0xIchigo commented on tests/webhook/test_delete_webhook.rs
> +    //assert!(response.is_ok(), "The API call failed: {:?}", response.err());
I've merged #28 to fix how we handle empty response bodies so we can test deleting webhooks no problem now

2024-05-23 22:48 UTC, davidkathoh commented
I  think all should be good now

2024-05-24 04:35 UTC, 0xIchigo approved these changes
LGTM 🔥

2024-05-24 04:35 UTC, 0xIchigo commented
Thank you for your contribution!

2024-05-24 04:35 UTC, merged